# This is a basic workflow to help you get started with Actions

name: Workflow to deploy to cloud hub

# Controls when the workflow will run
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Print effective-settings
        run: mvn help:effective-settings
        
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: target/*.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: artifacts
    - name: Deploy to CloudHub
      env:
        USERNAME: ${{ secrets.ANYPOINT_USERNAME_SANDBOX }}
        PASSWORD: ${{ secrets.ANYPOINT_PASSWORD_SANDBOX }}
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy -DmuleDeploy \
        -Dmule.artifact=$artifactName \
        -Danypoint.env=Sandbox \
        -Danypoint.appName=cicd-myfirstone \
        -Danypoint.username=$USERNAME \
        -Danypoint.password=$PASSWORD \
        -Danypoint.muleVersion=4.4.0 \
        -Danypoint.region=us-east-2 \
        -Danypoint.workers=1 \
        -DdeploymentTimeout=1000000 \
        -DskipTests
